apiVersion: apps/v1
kind: Deployment
metadata:
  name: chmodcalcapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chmodcalcapp
  template:
    metadata:
      labels:
        app: chmodcalcapp
    spec:
      containers:
        - name: chmodcalcapp
          image: dielawnk8s/chmodcalcapp:v4.0
          ports:
            - containerPort: 8501

---

apiVersion: v1
kind: Service
metadata:
  name: chmodcalcapp-service
spec:
  type: LoadBalancer
  selector:
    app: chmodcalcapp
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
